export enum AppMode {
  HOME = 'HOME',
  SENDER = 'SENDER',
  RECEIVER = 'RECEIVER',
}

export enum TransferStatus {
  IDLE = 'IDLE',
  SCANNING = 'SCANNING',
  CONNECTING = 'CONNECTING',
  TRANSFERRING = 'TRANSFERRING',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
}

export interface FileMeta {
  id: string;
  name: string;
  size: number;
  type: string;
  previewUrl?: string;
  aiSummary?: string; // Generated by Gemini
}

export interface Peer {
  id: string;
  name: string;
  device: 'mobile' | 'desktop' | 'tablet';
  status: 'available' | 'busy';
}
